### ISSUE TITLE
Samba 4.12 is out

### ISSUE THREAD

**Issue by nkadel** [sergiomb2/SambaAD#1]
Samba 4.12 has  been released. You're very welcome to my work elsewhere if ti helps. I'm having a bit of trouble with activating the compat-gnutls for it for CentOs 7, though CentOS 8 and Fedora 31 are so far coming along.

**Comment by sergiomb2** [comment]
hum, did you check my latest commits on compat-gnutls34 [1] ?

[1]
https://github.com/sergiomb2/SambaAD/commit/86e6d199a94ef7a00c6b6d42220786f6213a4db9#diff-5c04a0f3240609cd7cf30981d937373f

https://github.com/sergiomb2/SambaAD/commit/ade3252bd581f0203c3bb39fdeaf3aa0b61e5786#diff-5c04a0f3240609cd7cf30981d937373f

https://github.com/sergiomb2/SambaAD/commits/master/compat-gnutls34

**Comment by sergiomb2** [comment]
`/usr/bin/pkg-config "gnutls >= 3.4.7" --cflags --libs gnutls` check if it is working !

**Comment by nkadel** [comment]
I've previously imported your structures to https://github.com/nkadel/samba-4.12.x-srpm/blob/master/samba.spec .I split each SRPM repository into its own distinct repo, so that repo is specifically for samba itself.

The pkg-config command *reports* usable information, but it's not clear to me that the settings are actually getting inherited and loaded into the relevant CFLAGS and LDFLAGS used by the %conigure macro generated by the .spec file and passwd appropriately to the Samba ./configure file itself. That's  partly why I reached out. I don't understand your "pkg-config" comannd actually does anything, since it's apparently not setting any environment values.

**Comment by sergiomb2** [comment]
[1] set the PKG_CONFIG_PATH and `/usr/bin/pkg-config "gnutls >= 3.4.7" --cflags --libs gnutls` it is only to check if it is working, but doesn't set nothing and of course can be deleted . 
./configure use  pkg-config to detect libraries 

[1]
export PKG_CONFIG_PATH=%{_libdir}/compat-gnutls34/pkgconfig:%{_libdir}/compat-nettle32/pkgconfig

**Comment by nkadel** [comment]
samba 4.13 is in pre-release, and work is happening for that. I've brought over your latest compat updates to compat-nettle34 and compat-gnutls36.
